services:
  textUtilsBot:
    build: .
    image: kozalo/textutilsbot
    container_name: textUtilsBot
    working_dir: /home/textUtilsBot
    env_file:
      - path: .env
        required: false
    restart: unless-stopped
    expose:
      - "8080"
      - "8000"
    volumes:
      - "./app/config/currates_conf.py:/home/textUtilsBot/app/config/currates_conf.py"
      - "./data:/home/textUtilsBot/app/data"
      - "/tmp:/tmp"
    logging:
      driver: local
