version: "3"
services:
  textUtilsBot:
    build: .
    image: kozalo/textutilsbot
    container_name: textutilsbot
    hostname: testUtilsBot
    working_dir: /home/textUtilsBot
    restart: always
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
    - "./app/data:/home/textUtilsBot/app/data"
    - "/tmp:/tmp"
    logging:
      driver: local
