[project]
name = "textutilsbot"
version = "0.1.0"
description = "A simple bot for Telegram, that has some useful handlers of inline queries to make text conversions."
requires-python = ">=3.14"
dependencies = [
    "aiohttp==3.13.5",
    "aiohttp-socks>=0.11.0",
    "aiotg>=2.0.0",
    "asyncache>=0.3.1",
    "cachetools==5.5.2",
    "coverage>=7.14.0",
    "grpcio>=1.80.0",
    "klocmod>=0.3.1",
    "prometheus-client==0.25.0",
    "protobuf>=7.35.0",
    "requests==2.34.2",
]
