# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dto.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdto.proto\x12\x0cuser_service\"?\n\x0c\x45xternalUser\x12\x13\n\x0b\x65xternal_id\x18\x01 \x01(\x03\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\"\xe4\x01\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\x04name\x18\x02 \x01(\tH\x00\x88\x01\x01\x12+\n\x07options\x18\x03 \x01(\x0b\x32\x1a.user_service.User.Options\x12\x12\n\nis_premium\x18\x04 \x01(\x08\x1as\n\x07Options\x12\x1a\n\rlanguage_code\x18\x01 \x01(\tH\x00\x88\x01\x01\x12-\n\x08location\x18\x02 \x01(\x0b\x32\x16.user_service.LocationH\x01\x88\x01\x01\x42\x10\n\x0e_language_codeB\x0b\n\t_locationB\x07\n\x05_name\"/\n\x08Location\x12\x10\n\x08latitude\x18\x01 \x01(\x01\x12\x11\n\tlongitude\x18\x02 \x01(\x01\"@\n\x07Service\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\'\n\x04kind\x18\x02 \x01(\x0e\x32\x19.user_service.ServiceType*\xa5\x01\n\x0bServiceType\x12\x1c\n\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n\x19SERVICE_TYPE_TELEGRAM_BOT\x10\x01\x12!\n\x1dSERVICE_TYPE_TELEGRAM_CHANNEL\x10\x02\x12\x18\n\x14SERVICE_TYPE_WEBSITE\x10\x03\x12\x1c\n\x18SERVICE_TYPE_APPLICATION\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dto_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SERVICETYPE']._serialized_start=439
  _globals['_SERVICETYPE']._serialized_end=604
  _globals['_EXTERNALUSER']._serialized_start=27
  _globals['_EXTERNALUSER']._serialized_end=90
  _globals['_USER']._serialized_start=93
  _globals['_USER']._serialized_end=321
  _globals['_USER_OPTIONS']._serialized_start=197
  _globals['_USER_OPTIONS']._serialized_end=312
  _globals['_LOCATION']._serialized_start=323
  _globals['_LOCATION']._serialized_end=370
  _globals['_SERVICE']._serialized_start=372
  _globals['_SERVICE']._serialized_end=436
# @@protoc_insertion_point(module_scope)
