# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reqresp.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
import dto_pb2 as dto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreqresp.proto\x12\x0cuser_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\tdto.proto\"4\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x16\n\x0e\x62y_external_id\x18\x02 \x01(\x08\"i\n\x11UpdateUserRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x12\n\x08language\x18\x02 \x01(\tH\x00\x12*\n\x08location\x18\x03 \x01(\x0b\x32\x16.user_service.LocationH\x00\x42\x08\n\x06target\"\x96\x01\n\x13RegistrationRequest\x12(\n\x04user\x18\x01 \x01(\x0b\x32\x1a.user_service.ExternalUser\x12&\n\x07service\x18\x02 \x01(\x0b\x32\x15.user_service.Service\x12-\n\x0c\x63onsent_info\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"T\n\x14RegistrationResponse\x12\x30\n\x06status\x18\x01 \x01(\x0e\x32 .user_service.RegistrationStatus\x12\n\n\x02id\x18\x02 \x01(\x03\"S\n\x16\x41\x63tivatePremiumRequest\x12\n\n\x02id\x18\x01 \x01(\x03\x12-\n\x07variant\x18\x02 \x01(\x0e\x32\x1c.user_service.PremiumVariant\"p\n\x17\x41\x63tivatePremiumResponse\x12\x0f\n\x07updated\x18\x01 \x01(\x08\x12\x34\n\x0b\x61\x63tive_till\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x00\x88\x01\x01\x42\x0e\n\x0c_active_till*\x83\x01\n\x12RegistrationStatus\x12#\n\x1fREGISTRATION_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n\x1bREGISTRATION_STATUS_CREATED\x10\x01\x12\'\n#REGISTRATION_STATUS_ALREADY_PRESENT\x10\x02*\xa2\x01\n\x0ePremiumVariant\x12\x1f\n\x1bPREMIUM_VARIANT_UNSPECIFIED\x10\x00\x12\x19\n\x15PREMIUM_VARIANT_MONTH\x10\x01\x12\x1b\n\x17PREMIUM_VARIANT_QUARTER\x10\x02\x12\x1d\n\x19PREMIUM_VARIANT_HALF_YEAR\x10\x03\x12\x18\n\x14PREMIUM_VARIANT_YEAR\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reqresp_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REGISTRATIONSTATUS']._serialized_start=705
  _globals['_REGISTRATIONSTATUS']._serialized_end=836
  _globals['_PREMIUMVARIANT']._serialized_start=839
  _globals['_PREMIUMVARIANT']._serialized_end=1001
  _globals['_GETUSERREQUEST']._serialized_start=105
  _globals['_GETUSERREQUEST']._serialized_end=157
  _globals['_UPDATEUSERREQUEST']._serialized_start=159
  _globals['_UPDATEUSERREQUEST']._serialized_end=264
  _globals['_REGISTRATIONREQUEST']._serialized_start=267
  _globals['_REGISTRATIONREQUEST']._serialized_end=417
  _globals['_REGISTRATIONRESPONSE']._serialized_start=419
  _globals['_REGISTRATIONRESPONSE']._serialized_end=503
  _globals['_ACTIVATEPREMIUMREQUEST']._serialized_start=505
  _globals['_ACTIVATEPREMIUMREQUEST']._serialized_end=588
  _globals['_ACTIVATEPREMIUMRESPONSE']._serialized_start=590
  _globals['_ACTIVATEPREMIUMRESPONSE']._serialized_end=702
# @@protoc_insertion_point(module_scope)
