# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import dto_pb2 as dto__pb2
import reqresp_pb2 as reqresp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0cuser_service\x1a\x1bgoogle/protobuf/empty.proto\x1a\tdto.proto\x1a\rreqresp.proto2\xbc\x02\n\x0bUserService\x12\x37\n\x03get\x12\x1c.user_service.GetUserRequest\x1a\x12.user_service.User\x12Q\n\x08register\x12!.user_service.RegistrationRequest\x1a\".user_service.RegistrationResponse\x12\x41\n\x06update\x12\x1f.user_service.UpdateUserRequest\x1a\x16.google.protobuf.Empty\x12^\n\x0f\x61\x63tivatePremium\x12$.user_service.ActivatePremiumRequest\x1a%.user_service.ActivatePremiumResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_USERSERVICE']._serialized_start=87
  _globals['_USERSERVICE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
